-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 11:02:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdproyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdproyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS bdproyecto DEFAULT CHARACTER SET utf8 ;
USE bdproyecto ;

-- -----------------------------------------------------
-- Table bdproyecto.Area
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Area ;

CREATE TABLE IF NOT EXISTS bdproyecto.Area (
  id_area VARCHAR(15) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_area))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.TipoTrabajo
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.TipoTrabajo ;

CREATE TABLE IF NOT EXISTS bdproyecto.TipoTrabajo (
  id_tipoTrabajo VARCHAR(15) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_tipoTrabajo))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.TrabajoAcademico
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.TrabajoAcademico ;

CREATE TABLE IF NOT EXISTS bdproyecto.TrabajoAcademico (
  id_trabajoAcademico INT NOT NULL AUTO_INCREMENT,
  id_tipoTrabajo VARCHAR(15) NOT NULL,
  titulo VARCHAR(45) NOT NULL,
  descripcion VARCHAR(45) NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_final DATE NULL,
  id_area VARCHAR(15) NOT NULL,
  contenido BLOB NOT NULL,
  status VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_trabajoAcademico),
  INDEX FK_AreaTrabajo_idx (id_area ASC),
  INDEX FK_TipoTrabajo_idx (id_tipoTrabajo ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Estudiante
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Estudiante ;

CREATE TABLE IF NOT EXISTS bdproyecto.Estudiante (
  id_estudiante VARCHAR(10) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  apellido VARCHAR(45) NOT NULL,
  id_trabajoAcademico INT NULL,
  PRIMARY KEY (id_estudiante),
  INDEX fk_trabajoAcademico_idx (id_trabajoAcademico ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Departamento
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Departamento ;

CREATE TABLE IF NOT EXISTS bdproyecto.Departamento (
  id_departamento VARCHAR(15) NOT NULL,
  id_area VARCHAR(15) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_departamento),
  INDEX FK_Area_idx (id_area ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Docente
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Docente ;

CREATE TABLE IF NOT EXISTS bdproyecto.Docente (
  id_docente VARCHAR(10) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  apellido VARCHAR(45) NOT NULL,
  id_departamento VARCHAR(15) NOT NULL,
  PRIMARY KEY (id_docente),
  INDEX FK_Departamento_idx (id_departamento ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Users
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Users ;

CREATE TABLE IF NOT EXISTS bdproyecto.Users (
  id_user VARCHAR(40) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(60) NOT NULL,
  id_estudiante VARCHAR(10) NULL,
  id_docente VARCHAR(10) NULL,
  rol VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_user),
  INDEX fk_Users_Estudiante1_idx (id_estudiante ASC),
  INDEX fk_Users_Docente1_idx (id_docente ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Director_TrabajoAcademico
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Director_TrabajoAcademico ;

CREATE TABLE IF NOT EXISTS bdproyecto.Director_TrabajoAcademico (
  id_docente VARCHAR(10) NOT NULL,
  id_trabajoAcademico INT NOT NULL,
  INDEX fk_director_idx (id_docente ASC),
  INDEX fk_trabajoDirector_idx (id_trabajoAcademico ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Sinodal_TrabajoAcademico
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Sinodal_TrabajoAcademico ;

CREATE TABLE IF NOT EXISTS bdproyecto.Sinodal_TrabajoAcademico (
  id_sinodal VARCHAR(10) NOT NULL,
  id_trabajoAcademico INT NOT NULL,
  INDEX fk_sinodal_idx (id_sinodal ASC),
  INDEX fk_sinodalTrabajo_idx (id_trabajoAcademico ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.UsersTokens
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.UsersTokens ;

CREATE TABLE IF NOT EXISTS bdproyecto.UsersTokens (
  token VARCHAR(40) NOT NULL,
  dt_exp DATETIME NOT NULL,
  id_user VARCHAR(40) NOT NULL,
  PRIMARY KEY (token),
  INDEX fk_UsersTokens_Users1_idx (id_user ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.historial
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.historial ;

CREATE TABLE IF NOT EXISTS bdproyecto.historial (
  id_trabajoAcademico INT NULL,
  num_version VARCHAR(45) NULL,
  estatus VARCHAR(100) NULL,
  contenido BLOB NULL,
  INDEX fk_historialTrabajo_idx (id_trabajoAcademico ASC),
  CONSTRAINT fk_historialTrabajo
    FOREIGN KEY (id_trabajoAcademico)
    REFERENCES TrabajoAcademico (id_trabajoAcademico)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table bdproyecto.Titulacion
-- -----------------------------------------------------
DROP TABLE IF EXISTS bdproyecto.Titulacion ;

CREATE TABLE IF NOT EXISTS bdproyecto.Titulacion (
  id_titulacion INT NOT NULL AUTO_INCREMENT,
  tipo VARCHAR(45) NOT NULL,
  descripcion VARCHAR(1000) NOT NULL,
  PRIMARY KEY (id_titulacion))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;